// houston/components/common/Money.vue
<template>
    <span>{{ format(props.value, '$', 0, {spaceBetweenAmountAndSymbol: ' ', symbolOnLeft: false}) }}</span>
</template>

<script lang="ts" setup>
const props = defineProps<{ value: number }>();

function format(value: number, symbol: string | null, decimals: number | null, options: any) {
    let thousandsSeparator, symbolOnLeft, spaceBetweenAmountAndSymbol;
    const digitsRE = /(\d{3})(?=\d)/g;
    options = options || {};
    if (!isFinite(value) || (!value && value !== 0)) return '';
    symbol = symbol != null ? symbol : '$';
    decimals = decimals != null ? decimals : 2;
    thousandsSeparator = options.thousandsSeparator != null ? options.thousandsSeparator : ',';
    symbolOnLeft = options.symbolOnLeft != null ? options.symbolOnLeft : true;
    spaceBetweenAmountAndSymbol = options.spaceBetweenAmountAndSymbol != null ? options.spaceBetweenAmountAndSymbol : false;
    var stringified = Math.abs(value).toFixed(decimals);
    stringified = options.decimalSeparator ?
        stringified.replace('.', options.decimalSeparator) :
        stringified;
    var _int = decimals ?
        stringified.slice(0, -1 - decimals) :
        stringified;
    var i = _int.length % 3;
    var head = i > 0 ?
        (_int.slice(0, i) + (_int.length > 3 ? thousandsSeparator : '')) :
        '';
    var _float = decimals ?
        stringified.slice(-1 - decimals) :
        '';
    symbol = spaceBetweenAmountAndSymbol ?
        (symbolOnLeft ? symbol + ' ' : ' ' + symbol) :
        symbol;
    symbol = symbolOnLeft ?
        symbol + head +
        _int.slice(i).replace(digitsRE, '$1' + thousandsSeparator) + _float :
        head +
        _int.slice(i).replace(digitsRE, '$1' + thousandsSeparator) + _float + symbol;
    var sign = value < 0 ? '-' : '';
    return sign + symbol;
}
</script>

// front/src/components/common/Money.tsx
import React from 'react';

interface FormatProps {
	value: number;
}

const Money: React.FC<FormatProps> = ({ value }) => {
	function format(
		value: number,
		symbol: string | null = '$',
		decimals: number | null = 2,
		options: any = {}
	) {
		const digitsRE = /(\d{3})(?=\d)/g;
		if (!isFinite(value) || (!value && value !== 0)) return '';
		
		const {
			thousandsSeparator = ',',
			decimalSeparator = '.',
			symbolOnLeft = true,
			spaceBetweenAmountAndSymbol = false,
		} = options;
		
		const stringified = Math.abs(value).toFixed(decimals);
		const formattedValue = decimalSeparator
			? stringified.replace('.', decimalSeparator)
			: stringified;
		
		const _int = decimals
			? formattedValue.slice(0, -1 - decimals)
			: formattedValue;
		
		const i = _int.length % 3;
		const head =
			i > 0
				? _int.slice(0, i) +
				(_int.length > 3 ? thousandsSeparator : '')
				: '';
		const _float = decimals
			? formattedValue.slice(-1 - decimals)
			: '';
		
		symbol = spaceBetweenAmountAndSymbol
			? symbolOnLeft
				? symbol + ' '
				: ' ' + symbol
			: symbol;
		
		const result = symbolOnLeft
			? symbol +
			head +
			_int.slice(i).replace(digitsRE, '$1' + thousandsSeparator) +
			_float
			: head +
			_int.slice(i).replace(digitsRE, '$1' + thousandsSeparator) +
			_float +
			symbol;
		
		const sign = value < 0 ? '-' : '';
		return sign + result;
	}
	
	return (
		<span>
            {format(value, '$', 0, {
	            spaceBetweenAmountAndSymbol: ' ',
	            symbolOnLeft: false,
            })}
        </span>
	);
};

export default Money;
